spring:
  application:
    name: hsd-jenkins-ci
  profiles:
    active: dev
  jackson: 
    property-naming-strategy: LOWER_CAMEL_CASE 

server:
  port: 12306

management:
  security:
    enabled: false

info:
  name: "@project.name@"
  description: "@project.description@" 
  version: "@project.version@"
  spring-boot-version: "@project.parent.version@"  

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
    client:
        serviceUrl:
            defaultZone: http://${security.user.name}:${security.user.password}@localhost:9080/eureka/

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
            
swagger:
    basepackage: com.hsd.jenkins.web
    service:
        name: Jenkins-CI
        description: Jenkins-CI
        developer: Uname.CHEN

logging:
  level.root: info
  path: logs/

jenkinsci:
  swagger-open: true #是否开启swagger (true/false)
  
  
## Jenkins
jenkins:
  jenkins_url: http://192.168.254.240:88
  username: jenkins
  password: jenkins
  release_tag_prefix: V0.
  common_job_name: gold-jobs-template
  authors: chenfangri,tangyusheng
  